### ISSUE TITLE
MVC w3wp.exe terminated due to an unhandled exception using SQLServer session state

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetWebStack#139]
_From @sherwincool on March 9, 2018 6:27_

We are getting random (once or twice a day) `System.NullReferenceException` in our ASP.NET web application.

We are using SQLServer session state and a custom `GetControllerSessionBehavior`.

Here is the code:
``` c#
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    public sealed class ActionSessionStateAttribute : Attribute
    {
        public SessionStateBehavior Behavior { get; private set; }

        public ActionSessionStateAttribute(SessionStateBehavior behavior)
        {
            this.Behavior = behavior;
        }
    }

    public class CustomControllerFactory : DefaultControllerFactory
    {
        protected override SessionStateBehavior GetControllerSessionBehavior(RequestContext requestContext, Type controllerType)
        {
            //https://technologyatfingertips.wordpress.com/tag/mvc/
            if (controllerType == null)
                return SessionStateBehavior.Default;

            //https://stackoverflow.com/questions/10814147/how-can-i-get-the-methodinfo-of-the-controller-action-that-will-get-called-given

            ControllerContext controllerContext = new ControllerContext(requestContext, Activator.CreateInstance(controllerType) as ControllerBase);
            ControllerDescriptor controllerDescriptor = new ReflectedControllerDescriptor(controllerType);
            ActionDescriptor actionDescriptor = controllerDescriptor.FindAction(controllerContext, controllerContext.RouteData.Values["action"].ToString());

            MethodInfo cntMethodInfo = (actionDescriptor as ReflectedActionDescriptor).MethodInfo;

            if (cntMethodInfo != null)
            {
                var sessionStateAttr = cntMethodInfo.GetCustomAttributes(typeof(ActionSessionStateAttribute), false)
                                    .OfType<ActionSessionStateAttribute>()
                                    .FirstOrDefault();

                if (sessionStateAttr != null)
                {
                    return sessionStateAttr.Behavior;
                }
            }
            return base.GetControllerSessionBehavior(requestContext, controllerType);
        }
    }
```

Here how to use it in Action:
``` c#
[HttpGet]
[ActionSessionState(System.Web.SessionState.SessionStateBehavior.ReadOnly)]
public ActionResult LoadArchive([DataSourceRequest]DataSourceRequest request, int itemID)
{
        ///some codes here
}
```

And the event logs:
```
Log Name:      Application
Source:        Application Error
Date:          2/8/2018 4:36:03 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Computer.local
Description:
Faulting application name: w3wp.exe, version: 8.5.9600.16384, time stamp: 0x52157ba0
Faulting module name: System.Web.ni.dll, version: 4.7.2106.0, time stamp: 0x596675e4
Exception code: 0xc0000005
Fault offset: 0x0085b2bc
Faulting process id: 0xa524
Faulting application start time: 0x01d3a07fdd4d5fe5
Faulting application path: C:\Windows\SysWOW64\inetsrv\w3wp.exe
Faulting module path: C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Web\3e25306e79503ae2ebfbcaa5433a7e25\System.Web.ni.dll
Report Id: f33ab446-0c91-11e8-814b-06c7aabdd8ab
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-02-08T05:36:03.000000000Z" />
    <EventRecordID>166583</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Computer.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>w3wp.exe</Data>
    <Data>8.5.9600.16384</Data>
    <Data>52157ba0</Data>
    <Data>System.Web.ni.dll</Data>
    <Data>4.7.2106.0</Data>
    <Data>596675e4</Data>
    <Data>c0000005</Data>
    <Data>0085b2bc</Data>
    <Data>a524</Data>
    <Data>01d3a07fdd4d5fe5</Data>
    <Data>C:\Windows\SysWOW64\inetsrv\w3wp.exe</Data>
    <Data>C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Web\3e25306e79503ae2ebfbcaa5433a7e25\System.Web.ni.dll</Data>
    <Data>f33ab446-0c91-11e8-814b-06c7aabdd8ab</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          2/8/2018 4:36:03 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Computer.local
Description:
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Web.SessionState.SessionStateItemCollection.get_Item(Int32)
   at System.Web.SessionState.HttpSessionStateContainer.get_Item(Int32)
   at System.Web.Util.AspCompatApplicationStep.AnyStaObjectsInSessionState(System.Web.SessionState.HttpSessionState)
   at System.Web.HttpApplicationFactory.FireSessionOnEnd(System.Web.SessionState.HttpSessionState, System.Object, System.EventArgs)
   at System.Web.SessionState.SessionOnEndTargetWorkItem.RaiseOnEndCallback()
   at System.Web.Util.WorkItem.CallCallbackWithAssert(System.Web.Util.WorkItemCallback)
   at System.Web.Util.WorkItem.OnQueueUserWorkItemCompletion(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-02-08T05:36:03.000000000Z" />
    <EventRecordID>166582</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Computer.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Web.SessionState.SessionStateItemCollection.get_Item(Int32)
   at System.Web.SessionState.HttpSessionStateContainer.get_Item(Int32)
   at System.Web.Util.AspCompatApplicationStep.AnyStaObjectsInSessionState(System.Web.SessionState.HttpSessionState)
   at System.Web.HttpApplicationFactory.FireSessionOnEnd(System.Web.SessionState.HttpSessionState, System.Object, System.EventArgs)
   at System.Web.SessionState.SessionOnEndTargetWorkItem.RaiseOnEndCallback()
   at System.Web.Util.WorkItem.CallCallbackWithAssert(System.Web.Util.WorkItemCallback)
   at System.Web.Util.WorkItem.OnQueueUserWorkItemCompletion(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        ASP.NET 4.0.30319.0
Date:          2/8/2018 4:36:03 PM
Event ID:      1325
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Computer.local
Description:
An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/2/ROOT

Process ID: 42276

Exception: System.NullReferenceException

Message: Object reference not set to an instance of an object.

StackTrace:    at System.Web.SessionState.SessionStateItemCollection.get_Item(Int32 index)
   at System.Web.SessionState.HttpSessionStateContainer.get_Item(Int32 index)
   at System.Web.Util.AspCompatApplicationStep.AnyStaObjectsInSessionState(HttpSessionState session)
   at System.Web.HttpApplicationFactory.FireSessionOnEnd(HttpSessionState session, Object eventSource, EventArgs eventArgs)
   at System.Web.SessionState.SessionOnEndTargetWorkItem.RaiseOnEndCallback()
   at System.Web.Util.WorkItem.CallCallbackWithAssert(WorkItemCallback callback)
   at System.Web.Util.WorkItem.OnQueueUserWorkItemCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ASP.NET 4.0.30319.0" />
    <EventID Qualifiers="49152">1325</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-02-08T05:36:03.000000000Z" />
    <EventRecordID>166581</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Computer.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/2/ROOT

Process ID: 42276

Exception: System.NullReferenceException

Message: Object reference not set to an instance of an object.

StackTrace:    at System.Web.SessionState.SessionStateItemCollection.get_Item(Int32 index)
   at System.Web.SessionState.HttpSessionStateContainer.get_Item(Int32 index)
   at System.Web.Util.AspCompatApplicationStep.AnyStaObjectsInSessionState(HttpSessionState session)
   at System.Web.HttpApplicationFactory.FireSessionOnEnd(HttpSessionState session, Object eventSource, EventArgs eventArgs)
   at System.Web.SessionState.SessionOnEndTargetWorkItem.RaiseOnEndCallback()
   at System.Web.Util.WorkItem.CallCallbackWithAssert(WorkItemCallback callback)
   at System.Web.Util.WorkItem.OnQueueUserWorkItemCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()</Data>
  </EventData>
</Event>
```

_Copied from original issue: aspnet/Mvc#7461_

**Comment by mkArtakMSFT** [comment]
@dougbu, this seems to be old MVC related. Also, do you know who owns this area? Who this should be redirected to? Thanks!

**Comment by mkArtakMSFT** [comment]
Moving to ASPNETWebStack repo for now.

**Comment by dougbu** [comment]
@sherwincool you mentioned "once or twice a day". How many requests for the affected action(s) occur every day? Is anything obviously special about the time of day, the action(s), the data in the session state, &hellip; when problems occur?

If the application is reorganized to group actions sharing a `SessionStateBehavior` into controllers and to use `[SessionState]` on those controllers, do problems stop? This may be the recommendation because `DefaultControllerFactory` avoids allocating a controller instance and runtime reflection.

A few people here remember intentionally choosing *not* to support applying `[SessionState]` anywhere but on controller types. But, nobody remembers the exact reasons.

Failing all that, I am reaching out to the current System.Web owners.

**Comment by sherwincool** [comment]
Thank you @mkArtakMSFT for pointing this to correct repo.

Hi @dougbu, 

There is no specific time of day. Sometimes there we did not experince it in a day.

We also considered to use a separate controllers and set its SessionState but it was a big changes to our structure that why we look for other way.

Will you discuss further the DefaultControllerFactory avoids allocating a controller instance and runtime reflection.

Or should catch the error in DefaultControllerFactory and return the default SessionState?

Thank you very much.

**Comment by dougbu** [comment]
> the `DefaultControllerFactory` avoids allocating a controller instance and runtime reflection.

This class has no need of a controller instance. It caches `SessionStateBehavior` values in a `ConcurrentDictionary<Type, SessionStateBehavior>`, removing the need for subsequent reflection use.
> Or should catch the error in `DefaultControllerFactory` and return the default `SessionState`?

The `DefaultControllerFactory` may avoid any error.

**Comment by Jinhuafei** [comment]
@sherwincool  which version of mvc are you using? You are running your MVC app in IIS Classic mode?

**Comment by sherwincool** [comment]
We are using MVC v4 and running it in Integrated mode

**Comment by Jinhuafei** [comment]
Need more info about your app.

- 

-

**Comment by dougbu** [comment]
@Jinhuafei you're last comment didn't come through. What info should @sherwincool provide?

**Comment by sherwincool** [comment]
We are using COM in our application. I will check if there is a full memory dump.

will you please elavorate this 

> only the inproc sessionstate provider supports session end event.

**Comment by Jinhuafei** [comment]
Check "The Session_OnEnd event" on [this page](https://msdn.microsoft.com/en-us/library/ms178583.aspx). That's why I asked you what session provider you were using.

**Comment by sherwincool** [comment]
We are using SQLServer session state. I also check the like you provided but we are not using that event. We are using MvcApplication.Session_End(object sender, EventArgs e)

**Comment by Jinhuafei** [comment]
I still can't believe that using SQL sessionstate provider can cause this callstack. Do you have a simple repro app? Or a memory dump?

**Comment by sherwincool** [comment]
Sorry @Jinhuafei, I forgot that we did not yet implemented the SQLServer session state in PRODUCTION. We currently using INPROC session state. What would be the problem if we are using INPROC session state?

**Comment by Jinhuafei** [comment]
Do you have any code hold reference to HttpSessionState object(e.g. HttpContext.Session, HttpApplication.Session)? If so, do you remove items from it? 

If you switch to Sql sessionstate provider, you won't hit this issue. Also if you remove MvcApplication.Session_End, this won't bite you either.

**Comment by sherwincool** [comment]
Do you have any code hold reference to HttpSessionState object(e.g. HttpContext.Session, HttpApplication.Session)? If so, do you remove items from it?
 - We have codes that hold reference to HttpSessionState object

Do you know the content of this "at System.Web.SessionState.SessionStateItemCollection.get_Item(Int32 index)".

**Comment by dougbu** [comment]
@Jinhuafei is this issue external to Mvc? @sherwincool did @Jinhuafei's suggestion above solve your issue?
> If you switch to Sql sessionstate provider, you won't hit this issue. Also if you remove `MvcApplication.Session_End`, this won't bite you either.

**Comment by Jinhuafei** [comment]
So far I don't think it's related to MVC. The problem may be caused by the way how @sherwincool uses HttpSessionState. Would need a repro app to root cause the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by Peperud** [comment]
Seems like [AnyStaObjectsInSessionState](https://referencesource.microsoft.com/System.Web/R/75f5e33669ceb964.html) is simply not thread safe. 
While going through the session items (by index), the session storage is not locked. Another thread can remove items. And when it happens between these two calls:
```
at System.Web.SessionState.SessionStateItemCollection.get_Item(Int32 index)
at System.Web.SessionState.HttpSessionStateContainer.get_Item(Int32 index)
```
...the result can be a ```System.NullReferenceException```.

If there's a way to handle this gracefully it - that might also be acceptable, but as it is - it crashes the app pool.
