### ISSUE TITLE
Duplicate key exception due to race condition in UrlRewriterHelper.WasThisRequestRewritten()

### ISSUE THREAD

**Issue by flin-zap** [aspnet/AspNetWebStack#152]
In WasThisRequestRewritten(), 

the
`if (httpContext.Items.Contains((object) "IIS_WasUrlRewritten"))`
and 
`httpContext.Items.Add((object) "IIS_WasUrlRewritten", (object) "true");` or `"false"`

are not protected by a lock, so there can be a race condition when this is evaluated for the first time, and you get a duplicate key exception

**Comment by dougbu** [comment]
@flin-zap thank you for contacting us. To evaluate this ask, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve? Ideally, please share a repro as a GitHub repo.

**Comment by flin-zap** [comment]
Hi @dougbu 

During a request, we're making multiple calls to UrlHelper.Action() in parallel, which ultimately calls UrlRewriteHelper. This only happens when **IsUrlRewriterTurnedOn()** return true.

**Comment by dougbu** [comment]
Hi. Thanks for contacting us.

We're closing this issue as there was no much community interest in this ask for quite a while now.

**Comment by Shray007** [comment]
We are facing the same issue saying : System.ArgumentException: Item has already been added. Key in dictionary: 'IIS_WasUrlRewritten'  Key being added: 'IIS_WasUrlRewritten'.
Any update as to how to rectify this error ?

**Comment by flin-zap** [comment]
We've been working around it by _priming_ it at the start of the request :(

`new UrlHelper(HttpContext.Current.Request.RequestContext).Content("~/Dummy");`

**Comment by nikokkbg** [comment]
Hi @dougbu ,
Same problem. When you have an URL Rewrite Module and a UrlHelper.Action() in parallel we got this exception.  This is a crucial bug in this code. IsUrlRewriterTurnedOn has a thread safe execution and WasThisRequestRewritten not, why?

**Comment by cblaze22** [comment]
This still an issue? We have something similar and only happens on a certian production server.  This is baffling to us.

```
Error in Path :/177359/2021-2022-abybl-regular-season/schedule
Raw Url :/177359/2021-2022-abybl-regular-season/schedule
Message :Value does not fall within the expected range.
Source :mscorlib
Stack Trace :   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.IIS7WorkerRequest.GetServerVariableInternal(String name)
   at System.Web.WebPages.UrlRewriterHelper.WasThisRequestRewritten(HttpContextBase httpContext)
   at System.Web.WebPages.UrlUtil.GenerateClientUrlInternal(HttpContextBase httpContext, String contentPath)
   at System.Web.WebPages.UrlUtil.GenerateClientUrl(HttpContextBase httpContext, String contentPath)
   at System.Web.Mvc.UrlHelper.GenerateUrl(String routeName, String actionName, String controllerName, RouteValueDictionary routeValues, RouteCollection routeCollection, RequestContext requestContext, Boolean includeImplicitMvcValues)
   at System.Web.Mvc.UrlHelper.GenerateUrl(String routeName, String actionName, String controllerName, String protocol, String hostName, String fragment, RouteValueDictionary routeValues, RouteCollection routeCollection, RequestContext requestContext, Boolean includeImplicitMvcValues)
   at System.Web.Mvc.UrlHelper.RouteUrl(String routeName, RouteValueDictionary routeValues, String protocol, String hostName)
   at System.Web.Mvc.T4Extensions.Action(UrlHelper urlHelper, ActionResult result)```
