### ISSUE TITLE
Exception when replacing IBodyModelValidator 

### ISSUE THREAD

**Issue by vpaulino** [aspnet/AspNetWebStack#171]
Hi there, 

I was trying to change the behavior of  ShouldValidateType method on DefaultBodyModelValidator extending it and replacing it on the initialize method on the ApiController. 

 ```
protected override void Initialize(HttpControllerContext controllerContext)
        {                
                controllerContext.Configuration.Services.Replace(typeof(IBodyModelValidator), new CustomModelValidator());

        }
```

To debug the execution I override the ExecuteAsync method of my ApiController  like this:

   ```
public override async Task<HttpResponseMessage> ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
        {
         
            try
            {
                 
                var response = await base.ExecuteAsync(controllerContext, cancellationToken);
               
        
                return response;
            }
            catch (Exception ex)
            {

                throw;
            }
            
        }
```

And I'm catching a NullReferenceException with the following stack:
   

> 
> at System.Web.Http.Controllers.HttpActionBinding.ExecuteBindingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
>    at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEndAsync(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Func`1 execute, Action`1 endTrace, Action`1 errorTrace)
>    at System.Web.Http.Tracing.Tracers.HttpActionBindingTracer.ExecuteBindingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
>    at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at WebApiHost.Controllers.AnalysisEngineController.<ExecuteAsync>d__4.MoveNext() in C:\Users\vitor.paulino\source\repos\work\project\src\Sample\WebApiHost\Controllers\MyController.cs:line 61
 
The action method:

          [HttpPost]
        public IHttpActionResult Identify(MyComplexObject request)
        {
             
               var  response = ProcessInput(request);
                Console.WriteLine($"Leaving ProcessController.Identify {DateTime.UtcNow}");

                return Ok(response);
        
            
        }

the packages.config:
```

  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.6" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.6" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.6" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.OwinSelfHost" version="5.2.6" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Tracing" version="5.2.6" targetFramework="net471" />
  <package id="Microsoft.Owin" version="4.0.0" targetFramework="net471" />
  <package id="Microsoft.Owin.Host.HttpListener" version="2.0.2" targetFramework="net471" />
  <package id="Microsoft.Owin.Hosting" version="4.0.0" targetFramework="net471" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net471" />
  <package id="Owin" version="1.0" targetFramework="net471" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net471" />
  <package id="System.Memory" version="4.5.1" targetFramework="net471" />
  <package id="System.Numerics.Vectors" version="4.4.0" targetFramework="net471" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.0" targetFramework="net471" />

```
Any Ideias what might I'm doing wrong ? 

I have sample code reproducing the error here: 
https://github.com/vpaulino/aspnet-samples/commit/e698fef7085f4f6cdac724bf0303ac93152102a1

Thks in advance !

**Comment by vpaulino** [comment]
Hi there, 

I change the place where i replaced the IModelValidator and the error does not happen anymore.  I change that replacement to Startup class.
