### ISSUE TITLE
A couple of tests are flakey

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetWebStack#41]
See the following occasionally when building this repo locally. Haven't seen either failure on the CI but that rarely builds at all.
```
C:\dd\AspNetWebStack\tools\WebStack.xunit.targets(13,9): error : System.Web.Http.SelfHost.HttpSelfHostServerTest.SendAsync_ServiceModel_Throws_When_StreamContent_Throws(uri: "/SelfHostServerTest/ThrowBeforeWriteStream", transferMode: Buffered) [FAIL]
        Microsoft.TestCommon.Assert+ThrowsException : Assert.Throws() Failure
        Expected: typeof(System.Net.Http.HttpRequestException)
        Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
and
```
C:\dd\AspNetWebStack\test\System.Web.Mvc.Test\Test\DataAnnotationsModelValidatorTest.cs(99): error : System.Web.Mvc.Test.DataAnnotationsModelValidatorTest.NoClientRulesByDefault [FAIL] [C:\dd\AspNetWebStack\tools\WebStack.xunit.targets]
        System.InvalidOperationException : Operation is not valid due to the current state of the object.
             at Moq.MethodCall.Execute(ICallContext call)
             at Moq.MethodCallReturn`2.Execute(ICallContext call)
             at Moq.ExecuteCall.HandleIntercept(ICallContext invocation, InterceptorContext ctx, CurrentInterceptContext localctx)
             at Moq.Interceptor.Intercept(ICallContext invocation)
             at Moq.Proxy.CastleProxyFactory.Interceptor.Intercept(IInvocation invocation)
             at Castle.DynamicProxy.AbstractInvocation.Proceed()
             at Castle.Proxies.ModelMetadataProviderProxy.GetMetadataForProperty(Func`1 modelAccessor, Type containerType, String propertyName)
          C:\dd\AspNetWebStack\test\System.Web.Mvc.Test\Test\DataAnnotationsModelValidatorTest.cs(99,0): at System.Web.Mvc.Test.DataAnnotationsModelValidatorTest.NoClientRulesByDefault()
```

**Comment by dougbu** [comment]
f0988360
