### ISSUE TITLE
ASP.NET MVC AntiforgeryToken missing issue

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#48]
_From @kyajiv on September 10, 2016 12:40_

AntiforgeryToken doesn't work if user browse the website using googleweblight.

System.Web.Mvc.HttpAntiForgeryException (0x80004005): The required anti-forgery form field "__RequestVerificationToken" is not present.
   at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext)
   at System.Web.Helpers.AntiForgery.Validate()
   at System.Web.Mvc.ValidateAntiForgeryTokenAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)

_Copied from original issue: aspnet/Mvc#5263_

**Comment by dougbu** [comment]
@kyajiv for antiforgery to work, the hidden field is required and it appears Google WebLight is stripping it out.
