### ISSUE TITLE
Action Selection throws on invalid jQuery query string syntax

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetWebStack#54]
A URL like `http://example.com/?[&]`

Will result in the following exception:
```
The key is invalid JQuery syntax because it is missing a closing bracket
Parameter name: key","ExceptionType":"System.ArgumentException","StackTrace":"   
   at System.Web.Http.ModelBinding.FormDataCollectionExtensions.NormalizeJQueryToMvc(String key)
   at System.Web.Http.ModelBinding.FormDataCollectionExtensions.<GetJQueryNameValuePairs>d__0.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Net.Http.HttpRequestMessageExtensions.GetQueryNameValuePairs(HttpRequestMessage request)
   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.GetCandidateActionsWithBindings(HttpControllerContext controllerContext, CandidateAction[] candidatesFound)
   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.FindMatchingActions(HttpControllerContext controllerContext, Boolean ignoreVerbs)
   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()

```

This should result in a 400 (not a 500) or even better, no error at all, as who says you're following the jQuery format anyway

**Comment by rynowak** [comment]
The workaround for this is register an error handler like the following:
```
internal class MyExceptionHandler : IExceptionHandler
    {
        public Task HandleAsync(ExceptionHandlerContext context, CancellationToken cancellationToken)
        {
            if (!context.CatchBlock.IsTopLevel)
            {
                // Only handle exceptions on the last chance
                return Task.CompletedTask;
            }

            if (context.CatchBlock == ExceptionCatchBlocks.HttpControllerDispatcher &&
                context.Exception is ArgumentException)
            {
                // This is very likely your issue with the query string parsing, feel free to respond in
                // any way that's appropriate.
                var configuration = context.RequestContext.Configuration;
                context.Result = new BadRequestErrorMessageResult(
                    "You've been bad",
                    (IContentNegotiator)configuration.Services.GetService(typeof(IContentNegotiator)),
                    context.Request,
                    configuration.Formatters);
            }
            else
            {
                context.Result = new ResponseMessageResult(
                    context.Request.CreateErrorResponse(
                        HttpStatusCode.InternalServerError, 
                        context.Exception));
            }

            return Task.CompletedTask;
        }
    }

```

**Comment by oliverjanik** [comment]
I've hit this so many times it's not even funny. Who at Microsoft thought validating JQuery syntax serverside was a good idea? It's completely and utterly nuts.

Is there a way to turn this off completely?

**Comment by mkArtakMSFT** [comment]
Closing this as there is a [workaround available](https://github.com/aspnet/AspNetWebStack/issues/54#issuecomment-316910443) and this is not a critical blocking issue.

**Comment by kgriffs** [comment]
Can this be reconsidered? A partner of ours ran into this and it caused a production incident. The existence of a workaround is insufficient because it does not prevent the error until damage has already been done and people go looking and find this GH issue.
